#ifndef MULTIK_MULTIK_NATIVE_MULTIK_JNI_SRC_MAIN_HEADERS_COMPLEXFLOAT_H_
#define MULTIK_MULTIK_NATIVE_MULTIK_JNI_SRC_MAIN_HEADERS_COMPLEXFLOAT_H_

#include "jni.h"

jobject newComplexFloat(JNIEnv *, float, float);

#endif //MULTIK_MULTIK_NATIVE_MULTIK_JNI_SRC_MAIN_HEADERS_COMPLEXFLOAT_H_
