#ifndef MULTIK_MULTIK_NATIVE_MULTIK_JNI_SRC_MAIN_HEADERS_COMPLEXDOUBLE_H_
#define MULTIK_MULTIK_NATIVE_MULTIK_JNI_SRC_MAIN_HEADERS_COMPLEXDOUBLE_H_

#include "jni.h"

jobject newComplexDouble(JNIEnv *, double, double);

#endif //MULTIK_MULTIK_NATIVE_MULTIK_JNI_SRC_MAIN_HEADERS_COMPLEXDOUBLE_H_
