/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jetbrains_kotlinx_multik_jni_math_JniMath */

#ifndef _Included_org_jetbrains_kotlinx_multik_jni_math_JniMath
#define _Included_org_jetbrains_kotlinx_multik_jni_math_JniMath
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jetbrains_kotlinx_multik_jni_math_JniMath
 * Method:    argMax
 * Signature: (Ljava/lang/Object;II[I[II)I
 */
JNIEXPORT jint JNICALL Java_org_jetbrains_kotlinx_multik_jni_math_JniMath_argMax
	(JNIEnv *, jobject, jobject, jint, jint, jintArray, jintArray, jint);

/*
 * Class:     org_jetbrains_kotlinx_multik_jni_math_JniMath
 * Method:    argMin
 * Signature: (Ljava/lang/Object;II[I[II)I
 */
JNIEXPORT jint JNICALL Java_org_jetbrains_kotlinx_multik_jni_math_JniMath_argMin
	(JNIEnv *, jobject, jobject, jint, jint, jintArray, jintArray, jint);

/*
 * Class:     org_jetbrains_kotlinx_multik_jni_math_JniMath
 * Method:    exp
 * Signature: ([FI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jetbrains_kotlinx_multik_jni_math_JniMath_exp___3FI
	(JNIEnv *, jobject, jfloatArray, jint);

/*
 * Class:     org_jetbrains_kotlinx_multik_jni_math_JniMath
 * Method:    exp
 * Signature: ([DI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jetbrains_kotlinx_multik_jni_math_JniMath_exp___3DI
	(JNIEnv *, jobject, jdoubleArray, jint);

/*
 * Class:     org_jetbrains_kotlinx_multik_jni_math_JniMath
 * Method:    expC
 * Signature: ([FI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jetbrains_kotlinx_multik_jni_math_JniMath_expC___3FI
	(JNIEnv *, jobject, jfloatArray, jint);

/*
 * Class:     org_jetbrains_kotlinx_multik_jni_math_JniMath
 * Method:    expC
 * Signature: ([DI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jetbrains_kotlinx_multik_jni_math_JniMath_expC___3DI
	(JNIEnv *, jobject, jdoubleArray, jint);

/*
 * Class:     org_jetbrains_kotlinx_multik_jni_math_JniMath
 * Method:    log
 * Signature: ([FI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jetbrains_kotlinx_multik_jni_math_JniMath_log___3FI
	(JNIEnv *, jobject, jfloatArray, jint);

/*
 * Class:     org_jetbrains_kotlinx_multik_jni_math_JniMath
 * Method:    log
 * Signature: ([DI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jetbrains_kotlinx_multik_jni_math_JniMath_log___3DI
	(JNIEnv *, jobject, jdoubleArray, jint);

/*
 * Class:     org_jetbrains_kotlinx_multik_jni_math_JniMath
 * Method:    logC
 * Signature: ([FI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jetbrains_kotlinx_multik_jni_math_JniMath_logC___3FI
	(JNIEnv *, jobject, jfloatArray, jint);

/*
 * Class:     org_jetbrains_kotlinx_multik_jni_math_JniMath
 * Method:    logC
 * Signature: ([DI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jetbrains_kotlinx_multik_jni_math_JniMath_logC___3DI
	(JNIEnv *, jobject, jdoubleArray, jint);

/*
 * Class:     org_jetbrains_kotlinx_multik_jni_math_JniMath
 * Method:    sin
 * Signature: ([FI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jetbrains_kotlinx_multik_jni_math_JniMath_sin___3FI
	(JNIEnv *, jobject, jfloatArray, jint);

/*
 * Class:     org_jetbrains_kotlinx_multik_jni_math_JniMath
 * Method:    sin
 * Signature: ([DI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jetbrains_kotlinx_multik_jni_math_JniMath_sin___3DI
	(JNIEnv *, jobject, jdoubleArray, jint);

/*
 * Class:     org_jetbrains_kotlinx_multik_jni_math_JniMath
 * Method:    sinC
 * Signature: ([FI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jetbrains_kotlinx_multik_jni_math_JniMath_sinC___3FI
	(JNIEnv *, jobject, jfloatArray, jint);

/*
 * Class:     org_jetbrains_kotlinx_multik_jni_math_JniMath
 * Method:    sinC
 * Signature: ([DI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jetbrains_kotlinx_multik_jni_math_JniMath_sinC___3DI
	(JNIEnv *, jobject, jdoubleArray, jint);

/*
 * Class:     org_jetbrains_kotlinx_multik_jni_math_JniMath
 * Method:    cos
 * Signature: ([FI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jetbrains_kotlinx_multik_jni_math_JniMath_cos___3FI
	(JNIEnv *, jobject, jfloatArray, jint);

/*
 * Class:     org_jetbrains_kotlinx_multik_jni_math_JniMath
 * Method:    cos
 * Signature: ([DI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jetbrains_kotlinx_multik_jni_math_JniMath_cos___3DI
	(JNIEnv *, jobject, jdoubleArray, jint);

/*
 * Class:     org_jetbrains_kotlinx_multik_jni_math_JniMath
 * Method:    cosC
 * Signature: ([FI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jetbrains_kotlinx_multik_jni_math_JniMath_cosC___3FI
	(JNIEnv *, jobject, jfloatArray, jint);

/*
 * Class:     org_jetbrains_kotlinx_multik_jni_math_JniMath
 * Method:    cosC
 * Signature: ([DI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jetbrains_kotlinx_multik_jni_math_JniMath_cosC___3DI
	(JNIEnv *, jobject, jdoubleArray, jint);

/*
 * Class:     org_jetbrains_kotlinx_multik_jni_math_JniMath
 * Method:    array_max
 * Signature: (Ljava/lang/Object;II[I[II)Ljava/lang/Number;
 */
JNIEXPORT jobject JNICALL Java_org_jetbrains_kotlinx_multik_jni_math_JniMath_array_1max
	(JNIEnv *, jobject, jobject, jint, jint, jintArray, jintArray, jint);

/*
 * Class:     org_jetbrains_kotlinx_multik_jni_math_JniMath
 * Method:    array_min
 * Signature: (Ljava/lang/Object;II[I[II)Ljava/lang/Number;
 */
JNIEXPORT jobject JNICALL Java_org_jetbrains_kotlinx_multik_jni_math_JniMath_array_1min
	(JNIEnv *, jobject, jobject, jint, jint, jintArray, jintArray, jint);

/*
 * Class:     org_jetbrains_kotlinx_multik_jni_math_JniMath
 * Method:    sum
 * Signature: (Ljava/lang/Object;II[I[II)Ljava/lang/Number;
 */
JNIEXPORT jobject JNICALL Java_org_jetbrains_kotlinx_multik_jni_math_JniMath_sum
	(JNIEnv *, jobject, jobject, jint, jint, jintArray, jintArray, jint);

/*
 * Class:     org_jetbrains_kotlinx_multik_jni_math_JniMath
 * Method:    cumSum
 * Signature: (Ljava/lang/Object;II[I[ILjava/lang/Object;II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jetbrains_kotlinx_multik_jni_math_JniMath_cumSum
	(JNIEnv *, jobject, jobject, jint, jint, jintArray, jintArray, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
