/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jetbrains_kotlinx_multik_jni_linalg_JniLinAlg */

#ifndef _Included_org_jetbrains_kotlinx_multik_jni_linalg_JniLinAlg
#define _Included_org_jetbrains_kotlinx_multik_jni_linalg_JniLinAlg
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jetbrains_kotlinx_multik_jni_linalg_JniLinAlg
 * Method:    pow
 * Signature: ([FI[F)V
 */
JNIEXPORT void JNICALL Java_org_jetbrains_kotlinx_multik_jni_linalg_JniLinAlg_pow___3FI_3F
	(JNIEnv *, jobject, jfloatArray, jint, jfloatArray);

/*
 * Class:     org_jetbrains_kotlinx_multik_jni_linalg_JniLinAlg
 * Method:    pow
 * Signature: ([DI[D)V
 */
JNIEXPORT void JNICALL Java_org_jetbrains_kotlinx_multik_jni_linalg_JniLinAlg_pow___3DI_3D
	(JNIEnv *, jobject, jdoubleArray, jint, jdoubleArray);

/*
 * Class:     org_jetbrains_kotlinx_multik_jni_linalg_JniLinAlg
 * Method:    norm
 * Signature: ([FI)D
 */
JNIEXPORT jdouble JNICALL Java_org_jetbrains_kotlinx_multik_jni_linalg_JniLinAlg_norm___3FI
	(JNIEnv *, jobject, jfloatArray, jint);

/*
 * Class:     org_jetbrains_kotlinx_multik_jni_linalg_JniLinAlg
 * Method:    norm
 * Signature: ([DI)D
 */
JNIEXPORT jdouble JNICALL Java_org_jetbrains_kotlinx_multik_jni_linalg_JniLinAlg_norm___3DI
	(JNIEnv *, jobject, jdoubleArray, jint);

/*
 * Class:     org_jetbrains_kotlinx_multik_jni_linalg_JniLinAlg
 * Method:    inv
 * Signature: (I[FI)I
 */
JNIEXPORT jint JNICALL Java_org_jetbrains_kotlinx_multik_jni_linalg_JniLinAlg_inv__I_3FI
	(JNIEnv *, jobject, jint, jfloatArray, jint);

/*
 * Class:     org_jetbrains_kotlinx_multik_jni_linalg_JniLinAlg
 * Method:    inv
 * Signature: (I[DI)I
 */
JNIEXPORT jint JNICALL Java_org_jetbrains_kotlinx_multik_jni_linalg_JniLinAlg_inv__I_3DI
	(JNIEnv *, jobject, jint, jdoubleArray, jint);

/*
 * Class:     org_jetbrains_kotlinx_multik_jni_linalg_JniLinAlg
 * Method:    invC
 * Signature: (I[FI)I
 */
JNIEXPORT jint JNICALL Java_org_jetbrains_kotlinx_multik_jni_linalg_JniLinAlg_invC__I_3FI
	(JNIEnv *, jobject, jint, jfloatArray, jint);

/*
 * Class:     org_jetbrains_kotlinx_multik_jni_linalg_JniLinAlg
 * Method:    invC
 * Signature: (I[DI)I
 */
JNIEXPORT jint JNICALL Java_org_jetbrains_kotlinx_multik_jni_linalg_JniLinAlg_invC__I_3DI
	(JNIEnv *, jobject, jint, jdoubleArray, jint);

/*
 * Class:     org_jetbrains_kotlinx_multik_jni_linalg_JniLinAlg
 * Method:    qr
 * Signature: (II[FI[F)I
 */
JNIEXPORT jint JNICALL Java_org_jetbrains_kotlinx_multik_jni_linalg_JniLinAlg_qr__II_3FI_3F
	(JNIEnv *, jobject, jint, jint, jfloatArray, jint, jfloatArray);

/*
 * Class:     org_jetbrains_kotlinx_multik_jni_linalg_JniLinAlg
 * Method:    qr
 * Signature: (II[DI[D)I
 */
JNIEXPORT jint JNICALL Java_org_jetbrains_kotlinx_multik_jni_linalg_JniLinAlg_qr__II_3DI_3D
	(JNIEnv *, jobject, jint, jint, jdoubleArray, jint, jdoubleArray);

/*
 * Class:     org_jetbrains_kotlinx_multik_jni_linalg_JniLinAlg
 * Method:    qrC
 * Signature: (II[FI[F)I
 */
JNIEXPORT jint JNICALL Java_org_jetbrains_kotlinx_multik_jni_linalg_JniLinAlg_qrC__II_3FI_3F
	(JNIEnv *, jobject, jint, jint, jfloatArray, jint, jfloatArray);

/*
 * Class:     org_jetbrains_kotlinx_multik_jni_linalg_JniLinAlg
 * Method:    qrC
 * Signature: (II[DI[D)I
 */
JNIEXPORT jint JNICALL Java_org_jetbrains_kotlinx_multik_jni_linalg_JniLinAlg_qrC__II_3DI_3D
	(JNIEnv *, jobject, jint, jint, jdoubleArray, jint, jdoubleArray);

/*
 * Class:     org_jetbrains_kotlinx_multik_jni_linalg_JniLinAlg
 * Method:    solve
 * Signature: (II[FI[FI)I
 */
JNIEXPORT jint JNICALL Java_org_jetbrains_kotlinx_multik_jni_linalg_JniLinAlg_solve__II_3FI_3FI
	(JNIEnv *, jobject, jint, jint, jfloatArray, jint, jfloatArray, jint);

/*
 * Class:     org_jetbrains_kotlinx_multik_jni_linalg_JniLinAlg
 * Method:    solve
 * Signature: (II[DI[DI)I
 */
JNIEXPORT jint JNICALL Java_org_jetbrains_kotlinx_multik_jni_linalg_JniLinAlg_solve__II_3DI_3DI
	(JNIEnv *, jobject, jint, jint, jdoubleArray, jint, jdoubleArray, jint);

/*
 * Class:     org_jetbrains_kotlinx_multik_jni_linalg_JniLinAlg
 * Method:    solveC
 * Signature: (II[FI[FI)I
 */
JNIEXPORT jint JNICALL Java_org_jetbrains_kotlinx_multik_jni_linalg_JniLinAlg_solveC__II_3FI_3FI
	(JNIEnv *, jobject, jint, jint, jfloatArray, jint, jfloatArray, jint);

/*
 * Class:     org_jetbrains_kotlinx_multik_jni_linalg_JniLinAlg
 * Method:    solveC
 * Signature: (II[DI[DI)I
 */
JNIEXPORT jint JNICALL Java_org_jetbrains_kotlinx_multik_jni_linalg_JniLinAlg_solveC__II_3DI_3DI
	(JNIEnv *, jobject, jint, jint, jdoubleArray, jint, jdoubleArray, jint);

/*
 * Class:     org_jetbrains_kotlinx_multik_jni_linalg_JniLinAlg
 * Method:    dotMM
 * Signature: (ZI[FIIIZI[FII[F)V
 */
JNIEXPORT void JNICALL Java_org_jetbrains_kotlinx_multik_jni_linalg_JniLinAlg_dotMM__ZI_3FIIIZI_3FII_3F
	(JNIEnv *, jobject, jboolean, jint, jfloatArray, jint, jint, jint,
	 jboolean, jint, jfloatArray, jint, jint, jfloatArray);

/*
 * Class:     org_jetbrains_kotlinx_multik_jni_linalg_JniLinAlg
 * Method:    dotMM
 * Signature: (ZI[DIIIZI[DII[D)V
 */
JNIEXPORT void JNICALL Java_org_jetbrains_kotlinx_multik_jni_linalg_JniLinAlg_dotMM__ZI_3DIIIZI_3DII_3D
	(JNIEnv *, jobject, jboolean, jint, jdoubleArray, jint, jint, jint,
	 jboolean, jint, jdoubleArray, jint, jint, jdoubleArray);

/*
 * Class:     org_jetbrains_kotlinx_multik_jni_linalg_JniLinAlg
 * Method:    dotMMC
 * Signature: (ZI[FIIIZI[FII[F)V
 */
JNIEXPORT void JNICALL Java_org_jetbrains_kotlinx_multik_jni_linalg_JniLinAlg_dotMMC__ZI_3FIIIZI_3FII_3F
	(JNIEnv *, jobject, jboolean, jint, jfloatArray, jint, jint, jint,
	 jboolean, jint, jfloatArray, jint, jint, jfloatArray);

/*
 * Class:     org_jetbrains_kotlinx_multik_jni_linalg_JniLinAlg
 * Method:    dotMMC
 * Signature: (ZI[DIIIZI[DII[D)V
 */
JNIEXPORT void JNICALL Java_org_jetbrains_kotlinx_multik_jni_linalg_JniLinAlg_dotMMC__ZI_3DIIIZI_3DII_3D
	(JNIEnv *, jobject, jboolean, jint, jdoubleArray, jint, jint, jint,
	 jboolean, jint, jdoubleArray, jint, jint, jdoubleArray);

/*
 * Class:     org_jetbrains_kotlinx_multik_jni_linalg_JniLinAlg
 * Method:    dotMV
 * Signature: (ZI[FIII[FI[F)V
 */
JNIEXPORT void JNICALL Java_org_jetbrains_kotlinx_multik_jni_linalg_JniLinAlg_dotMV__ZI_3FIII_3FI_3F
	(JNIEnv *, jobject, jboolean, jint, jfloatArray, jint, jint, jint, jfloatArray, jint, jfloatArray);

/*
 * Class:     org_jetbrains_kotlinx_multik_jni_linalg_JniLinAlg
 * Method:    dotMV
 * Signature: (ZI[DIII[DI[D)V
 */
JNIEXPORT void JNICALL Java_org_jetbrains_kotlinx_multik_jni_linalg_JniLinAlg_dotMV__ZI_3DIII_3DI_3D
	(JNIEnv *, jobject, jboolean, jint, jdoubleArray, jint, jint, jint, jdoubleArray, jint, jdoubleArray);

/*
 * Class:     org_jetbrains_kotlinx_multik_jni_linalg_JniLinAlg
 * Method:    dotMVC
 * Signature: (ZI[FIII[FI[F)V
 */
JNIEXPORT void JNICALL Java_org_jetbrains_kotlinx_multik_jni_linalg_JniLinAlg_dotMVC__ZI_3FIII_3FI_3F
	(JNIEnv *, jobject, jboolean, jint, jfloatArray, jint, jint, jint, jfloatArray, jint, jfloatArray);

/*
 * Class:     org_jetbrains_kotlinx_multik_jni_linalg_JniLinAlg
 * Method:    dotMVC
 * Signature: (ZI[DIII[DI[D)V
 */
JNIEXPORT void JNICALL Java_org_jetbrains_kotlinx_multik_jni_linalg_JniLinAlg_dotMVC__ZI_3DIII_3DI_3D
	(JNIEnv *, jobject, jboolean, jint, jdoubleArray, jint, jint, jint, jdoubleArray, jint, jdoubleArray);

/*
 * Class:     org_jetbrains_kotlinx_multik_jni_linalg_JniLinAlg
 * Method:    dotVV
 * Signature: (I[FI[FI)F
 */
JNIEXPORT jfloat JNICALL Java_org_jetbrains_kotlinx_multik_jni_linalg_JniLinAlg_dotVV__I_3FI_3FI
	(JNIEnv *, jobject, jint, jfloatArray, jint, jfloatArray, jint);

/*
 * Class:     org_jetbrains_kotlinx_multik_jni_linalg_JniLinAlg
 * Method:    dotVV
 * Signature: (I[DI[DI)D
 */
JNIEXPORT jdouble JNICALL Java_org_jetbrains_kotlinx_multik_jni_linalg_JniLinAlg_dotVV__I_3DI_3DI
	(JNIEnv *, jobject, jint, jdoubleArray, jint, jdoubleArray, jint);

/*
 * Class:     org_jetbrains_kotlinx_multik_jni_linalg_JniLinAlg
 * Method:    dotVVC
 * Signature: (I[FI[FI)F
 */
JNIEXPORT jfloat JNICALL Java_org_jetbrains_kotlinx_multik_jni_linalg_JniLinAlg_dotVVC__I_3FI_3FI
	(JNIEnv *, jobject, jint, jfloatArray, jint, jfloatArray, jint);

/*
 * Class:     org_jetbrains_kotlinx_multik_jni_linalg_JniLinAlg
 * Method:    dotVVC
 * Signature: (I[DI[DI)D
 */
JNIEXPORT jdouble JNICALL Java_org_jetbrains_kotlinx_multik_jni_linalg_JniLinAlg_dotVVC__I_3DI_3DI
	(JNIEnv *, jobject, jint, jdoubleArray, jint, jdoubleArray, jint);

#ifdef __cplusplus
}
#endif
#endif
