/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg */

#ifndef _Included_org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg
#define _Included_org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg
 * Method:    pow
 * Signature: ([FI[F)V
 */
JNIEXPORT void JNICALL Java_org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg_pow___3FI_3F
	(JNIEnv *, jobject, jfloatArray, jint, jfloatArray);

/*
 * Class:     org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg
 * Method:    pow
 * Signature: ([DI[D)V
 */
JNIEXPORT void JNICALL Java_org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg_pow___3DI_3D
	(JNIEnv *, jobject, jdoubleArray, jint, jdoubleArray);

/*
 * Class:     org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg
 * Method:    norm
 * Signature: (CII[FI)F
 */
JNIEXPORT jfloat JNICALL Java_org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg_norm__CII_3FI
	(JNIEnv *, jobject, jchar, jint, jint, jfloatArray, jint);

/*
 * Class:     org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg
 * Method:    norm
 * Signature: (CII[DI)D
 */
JNIEXPORT jdouble JNICALL Java_org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg_norm__CII_3DI
	(JNIEnv *, jobject, jchar, jint, jint, jdoubleArray, jint);

/*
 * Class:     org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg
 * Method:    inv
 * Signature: (I[FI)I
 */
JNIEXPORT jint JNICALL Java_org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg_inv__I_3FI
	(JNIEnv *, jobject, jint, jfloatArray, jint);

/*
 * Class:     org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg
 * Method:    inv
 * Signature: (I[DI)I
 */
JNIEXPORT jint JNICALL Java_org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg_inv__I_3DI
	(JNIEnv *, jobject, jint, jdoubleArray, jint);

/*
 * Class:     org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg
 * Method:    invC
 * Signature: (I[FI)I
 */
JNIEXPORT jint JNICALL Java_org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg_invC__I_3FI
	(JNIEnv *, jobject, jint, jfloatArray, jint);

/*
 * Class:     org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg
 * Method:    invC
 * Signature: (I[DI)I
 */
JNIEXPORT jint JNICALL Java_org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg_invC__I_3DI
	(JNIEnv *, jobject, jint, jdoubleArray, jint);

/*
 * Class:     org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg
 * Method:    qr
 * Signature: (II[FI[F)I
 */
JNIEXPORT jint JNICALL Java_org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg_qr__II_3FI_3F
	(JNIEnv *, jobject, jint, jint, jfloatArray, jint, jfloatArray);

/*
 * Class:     org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg
 * Method:    qr
 * Signature: (II[DI[D)I
 */
JNIEXPORT jint JNICALL Java_org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg_qr__II_3DI_3D
	(JNIEnv *, jobject, jint, jint, jdoubleArray, jint, jdoubleArray);

/*
 * Class:     org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg
 * Method:    qrC
 * Signature: (II[FI[F)I
 */
JNIEXPORT jint JNICALL Java_org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg_qrC__II_3FI_3F
	(JNIEnv *, jobject, jint, jint, jfloatArray, jint, jfloatArray);

/*
 * Class:     org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg
 * Method:    qrC
 * Signature: (II[DI[D)I
 */
JNIEXPORT jint JNICALL Java_org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg_qrC__II_3DI_3D
	(JNIEnv *, jobject, jint, jint, jdoubleArray, jint, jdoubleArray);

/*
 * Class:     org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg
 * Method:    plu
 * Signature: (II[FI[I)I
 */
JNIEXPORT jint JNICALL Java_org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg_plu__II_3FI_3I
	(JNIEnv *, jobject, jint, jint, jfloatArray, jint, jintArray);

/*
 * Class:     org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg
 * Method:    plu
 * Signature: (II[DI[I)I
 */
JNIEXPORT jint JNICALL Java_org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg_plu__II_3DI_3I
	(JNIEnv *, jobject, jint, jint, jdoubleArray, jint, jintArray);

/*
 * Class:     org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg
 * Method:    pluC
 * Signature: (II[FI[I)I
 */
JNIEXPORT jint JNICALL Java_org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg_pluC__II_3FI_3I
	(JNIEnv *, jobject, jint, jint, jfloatArray, jint, jintArray);

/*
 * Class:     org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg
 * Method:    pluC
 * Signature: (II[DI[I)I
 */
JNIEXPORT jint JNICALL Java_org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg_pluC__II_3DI_3I
	(JNIEnv *, jobject, jint, jint, jdoubleArray, jint, jintArray);

/*
 * Class:     org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg
 * Method:    solve
 * Signature: (II[FI[FI)I
 */
JNIEXPORT jint JNICALL Java_org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg_solve__II_3FI_3FI
	(JNIEnv *, jobject, jint, jint, jfloatArray, jint, jfloatArray, jint);

/*
 * Class:     org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg
 * Method:    solve
 * Signature: (II[DI[DI)I
 */
JNIEXPORT jint JNICALL Java_org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg_solve__II_3DI_3DI
	(JNIEnv *, jobject, jint, jint, jdoubleArray, jint, jdoubleArray, jint);

/*
 * Class:     org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg
 * Method:    solveC
 * Signature: (II[FI[FI)I
 */
JNIEXPORT jint JNICALL Java_org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg_solveC__II_3FI_3FI
	(JNIEnv *, jobject, jint, jint, jfloatArray, jint, jfloatArray, jint);

/*
 * Class:     org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg
 * Method:    solveC
 * Signature: (II[DI[DI)I
 */
JNIEXPORT jint JNICALL Java_org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg_solveC__II_3DI_3DI
	(JNIEnv *, jobject, jint, jint, jdoubleArray, jint, jdoubleArray, jint);

/*
 * Class:     org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg
 * Method:    dotMM
 * Signature: (ZI[FIIIZI[FII[F)V
 */
JNIEXPORT void JNICALL Java_org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg_dotMM__ZI_3FIIIZI_3FII_3F
	(JNIEnv *, jobject, jboolean, jint, jfloatArray, jint, jint, jint,
	 jboolean, jint, jfloatArray, jint, jint, jfloatArray);

/*
 * Class:     org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg
 * Method:    dotMM
 * Signature: (ZI[DIIIZI[DII[D)V
 */
JNIEXPORT void JNICALL Java_org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg_dotMM__ZI_3DIIIZI_3DII_3D
	(JNIEnv *, jobject, jboolean, jint, jdoubleArray, jint, jint, jint,
	 jboolean, jint, jdoubleArray, jint, jint, jdoubleArray);

/*
 * Class:     org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg
 * Method:    dotMMC
 * Signature: (ZI[FIIIZI[FII[F)V
 */
JNIEXPORT void JNICALL Java_org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg_dotMMC__ZI_3FIIIZI_3FII_3F
	(JNIEnv *, jobject, jboolean, jint, jfloatArray, jint, jint, jint,
	 jboolean, jint, jfloatArray, jint, jint, jfloatArray);

/*
 * Class:     org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg
 * Method:    dotMMC
 * Signature: (ZI[DIIIZI[DII[D)V
 */
JNIEXPORT void JNICALL Java_org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg_dotMMC__ZI_3DIIIZI_3DII_3D
	(JNIEnv *, jobject, jboolean, jint, jdoubleArray, jint, jint, jint,
	 jboolean, jint, jdoubleArray, jint, jint, jdoubleArray);

/*
 * Class:     org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg
 * Method:    dotMV
 * Signature: (ZI[FIIII[FI[F)V
 */
JNIEXPORT void JNICALL Java_org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg_dotMV__ZI_3FIIII_3FI_3F
	(JNIEnv *, jobject, jboolean, jint, jfloatArray, jint, jint, jint, jint, jfloatArray, jint, jfloatArray);

/*
 * Class:     org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg
 * Method:    dotMV
 * Signature: (ZI[DIIII[DI[D)V
 */
JNIEXPORT void JNICALL Java_org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg_dotMV__ZI_3DIIII_3DI_3D
	(JNIEnv *, jobject, jboolean, jint, jdoubleArray, jint, jint, jint, jint, jdoubleArray, jint, jdoubleArray);

/*
 * Class:     org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg
 * Method:    dotMVC
 * Signature: (ZI[FIIII[FI[F)V
 */
JNIEXPORT void JNICALL Java_org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg_dotMVC__ZI_3FIIII_3FI_3F
	(JNIEnv *, jobject, jboolean, jint, jfloatArray, jint, jint, jint, jint, jfloatArray, jint, jfloatArray);

/*
 * Class:     org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg
 * Method:    dotMVC
 * Signature: (ZI[DIIII[DI[D)V
 */
JNIEXPORT void JNICALL Java_org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg_dotMVC__ZI_3DIIII_3DI_3D
	(JNIEnv *, jobject, jboolean, jint, jdoubleArray, jint, jint, jint, jint, jdoubleArray, jint, jdoubleArray);

/*
 * Class:     org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg
 * Method:    dotVV
 * Signature: (II[FII[FI)F
 */
JNIEXPORT jfloat JNICALL Java_org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg_dotVV__II_3FII_3FI
	(JNIEnv *, jobject, jint, jint, jfloatArray, jint, jint, jfloatArray, jint);

/*
 * Class:     org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg
 * Method:    dotVV
 * Signature: (II[DII[DI)D
 */
JNIEXPORT jdouble JNICALL Java_org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg_dotVV__II_3DII_3DI
	(JNIEnv *, jobject, jint, jint, jdoubleArray, jint, jint, jdoubleArray, jint);

/*
 * Class:     org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg
 * Method:    dotVVC
 * Signature: (II[FII[FI)Lorg/jetbrains/kotlinx/multik/ndarray/complex/ComplexFloat;
 */
JNIEXPORT jobject JNICALL Java_org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg_dotVVC__II_3FII_3FI
	(JNIEnv *, jobject, jint, jint, jfloatArray, jint, jint, jfloatArray, jint);

/*
 * Class:     org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg
 * Method:    dotVVC
 * Signature: (II[DII[DI)Lorg/jetbrains/kotlinx/multik/ndarray/complex/ComplexDouble;
 */
JNIEXPORT jobject JNICALL Java_org_jetbrains_kotlinx_multik_openblas_linalg_JniLinAlg_dotVVC__II_3DII_3DI
	(JNIEnv *, jobject, jint, jint, jdoubleArray, jint, jint, jdoubleArray, jint);

#ifdef __cplusplus
}
#endif
#endif
