/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jetbrains_kotlinx_multik_openblas_stat_JniStat */

#ifndef _Included_org_jetbrains_kotlinx_multik_openblas_stat_JniStat
#define _Included_org_jetbrains_kotlinx_multik_openblas_stat_JniStat
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jetbrains_kotlinx_multik_openblas_stat_JniStat
 * Method:    median
 * Signature: (Ljava/lang/Object;II)D
 */
JNIEXPORT jdouble JNICALL Java_org_jetbrains_kotlinx_multik_openblas_stat_JniStat_median
  (JNIEnv *, jobject, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
