/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jetbrains_multik_jni_JniLinAlg */

#ifndef _Included_org_jetbrains_multik_jni_JniLinAlg
#define _Included_org_jetbrains_multik_jni_JniLinAlg
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jetbrains_multik_jni_JniLinAlg
 * Method:    pow
 * Signature: (Lorg/jetbrains/multik/core/Ndarray;I)Lorg/jetbrains/multik/core/Ndarray;
 */
JNIEXPORT jobject JNICALL Java_org_jetbrains_multik_jni_JniLinAlg_pow
    (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     org_jetbrains_multik_jni_JniLinAlg
 * Method:    norm
 * Signature: (Lorg/jetbrains/multik/core/Ndarray;I)D
 */
JNIEXPORT jdouble JNICALL Java_org_jetbrains_multik_jni_JniLinAlg_norm
    (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     org_jetbrains_multik_jni_JniLinAlg
 * Method:    dot
 * Signature: ([FII[FI[F)V
 */
JNIEXPORT void JNICALL Java_org_jetbrains_multik_jni_JniLinAlg_dot___3FII_3FI_3F
    (JNIEnv *, jobject, jfloatArray, jint, jint, jfloatArray, jint, jfloatArray);

/*
 * Class:     org_jetbrains_multik_jni_JniLinAlg
 * Method:    dot
 * Signature: ([DII[DI[D)V
 */
JNIEXPORT void JNICALL Java_org_jetbrains_multik_jni_JniLinAlg_dot___3DII_3DI_3D
    (JNIEnv *, jobject, jdoubleArray, jint, jint, jdoubleArray, jint, jdoubleArray);

/*
 * Class:     org_jetbrains_multik_jni_JniLinAlg
 * Method:    dot
 * Signature: ([FII[F[F)V
 */
JNIEXPORT void JNICALL Java_org_jetbrains_multik_jni_JniLinAlg_dot___3FII_3F_3F
    (JNIEnv *, jobject, jfloatArray, jint, jint, jfloatArray, jfloatArray);

/*
 * Class:     org_jetbrains_multik_jni_JniLinAlg
 * Method:    dot
 * Signature: ([DII[D[D)V
 */
JNIEXPORT void JNICALL Java_org_jetbrains_multik_jni_JniLinAlg_dot___3DII_3D_3D
    (JNIEnv *, jobject, jdoubleArray, jint, jint, jdoubleArray, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
