/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jetbrains_multik_Basic */

#ifndef _NDARRAY_H_
#define _NDARRAY_H_

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jetbrains_multik_jni_Basic
 * Method:    allocate
 * Signature: (Ljava/nio/Buffer;[II)J
 */
JNIEXPORT jlong JNICALL Java_org_jetbrains_multik_jni_Basic_allocate
    (JNIEnv *, jobject, jobject, jintArray, jint);

/*
 * Class:     org_jetbrains_multik_jni_Basic
 * Method:    delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jetbrains_multik_jni_Basic_delete
    (JNIEnv *, jobject, jlong);

/*
 * Class:     org_jetbrains_multik_jni_Basic
 * Method:    delete
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_jetbrains_multik_jni_Basic_dot
    (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif //_NDARRAY_H_
