/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jetbrains_multik_jni_JniMath */

#ifndef _Included_org_jetbrains_multik_jni_JniMath
#define _Included_org_jetbrains_multik_jni_JniMath
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jetbrains_multik_jni_JniMath
 * Method:    argMax
 * Signature: (Ljava/lang/Object;II[I[II)I
 */
JNIEXPORT jint JNICALL Java_org_jetbrains_multik_jni_JniMath_argMax
    (JNIEnv *, jobject, jobject, jint, jint, jintArray, jintArray, jint);

/*
 * Class:     org_jetbrains_multik_jni_JniMath
 * Method:    argMin
 * Signature: (Ljava/lang/Object;II[I[II)I
 */
JNIEXPORT jint JNICALL Java_org_jetbrains_multik_jni_JniMath_argMin
    (JNIEnv *, jobject, jobject, jint, jint, jintArray, jintArray, jint);

/*
 * Class:     org_jetbrains_multik_jni_JniMath
 * Method:    exp
 * Signature: (Ljava/lang/Object;II[I[I[DI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jetbrains_multik_jni_JniMath_exp
    (JNIEnv *, jobject, jobject, jint, jint, jintArray, jintArray, jdoubleArray, jint);

/*
 * Class:     org_jetbrains_multik_jni_JniMath
 * Method:    log
 * Signature: (Ljava/lang/Object;II[I[I[DI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jetbrains_multik_jni_JniMath_log
    (JNIEnv *, jobject, jobject, jint, jint, jintArray, jintArray, jdoubleArray, jint);

/*
 * Class:     org_jetbrains_multik_jni_JniMath
 * Method:    sin
 * Signature: (Ljava/lang/Object;II[I[I[DI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jetbrains_multik_jni_JniMath_sin
    (JNIEnv *, jobject, jobject, jint, jint, jintArray, jintArray, jdoubleArray, jint);

/*
 * Class:     org_jetbrains_multik_jni_JniMath
 * Method:    cos
 * Signature: (Ljava/lang/Object;II[I[I[DI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jetbrains_multik_jni_JniMath_cos
    (JNIEnv *, jobject, jobject, jint, jint, jintArray, jintArray, jdoubleArray, jint);

/*
 * Class:     org_jetbrains_multik_jni_JniMath
 * Method:    max
 * Signature: (Ljava/lang/Object;II[I[II)Ljava/lang/Number;
 */
JNIEXPORT jobject JNICALL Java_org_jetbrains_multik_jni_JniMath_max
    (JNIEnv *, jobject, jobject, jint, jint, jintArray, jintArray, jint);

/*
 * Class:     org_jetbrains_multik_jni_JniMath
 * Method:    min
 * Signature: (Ljava/lang/Object;II[I[II)Ljava/lang/Number;
 */
JNIEXPORT jobject JNICALL Java_org_jetbrains_multik_jni_JniMath_min
    (JNIEnv *, jobject, jobject, jint, jint, jintArray, jintArray, jint);

/*
 * Class:     org_jetbrains_multik_jni_JniMath
 * Method:    sum
 * Signature: (Ljava/lang/Object;II[I[II)Ljava/lang/Number;
 */
JNIEXPORT jobject JNICALL Java_org_jetbrains_multik_jni_JniMath_sum
    (JNIEnv *, jobject, jobject, jint, jint, jintArray, jintArray, jint);

/*
 * Class:     org_jetbrains_multik_jni_JniMath
 * Method:    cumSum
 * Signature: (Ljava/lang/Object;II[I[ILjava/lang/Object;II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jetbrains_multik_jni_JniMath_cumSum
    (JNIEnv *, jobject, jobject, jint, jint, jintArray, jintArray, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
